---
title: "Expected Concepts Present Output Library"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_collapsed: yes
    toc_float: yes
---

```{r setup, include=FALSE}
# Default taken from R notebook behavior: when knitting, wd will always be location of notebook
base_dir <- '..'
Sys.setenv(PEDSNET_SKIP_REQUEST_EXECUTION=1)
tryCatch(source('../site/run.R'),
         error = function (e) message(e)) # May not be able to make db connection

# Set to "local" to read data from ../results, or another value to read from db
data_source <- if_else(config('execution_mode') == 'distribution', 'local', 'not_local')

require(tidyr)
require(knitr)
require(kableExtra)
require(stringr)
require(tibble)
require(ggplot2)
require(qicharts2)

get_results <- function(tbl_name) {
  if (data_source == 'local') {
    rslt <- read_csv(paste0('../results/', tbl_name, '.csv'))
  }
  else {
    rslt <- results_tbl(tbl_name) %>% collect()
  }
rslt
}

prettify_kable <- function(data) {
  data %>% kable(digits = 4, format.args = list(big.mark = ',')) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
    column_spec(1, bold = T, border_right = T)
}

no_time <- read_csv(file = paste0(config('base_dir'), '/results/ecp_nt.csv'))

across_time <- read_csv(file = paste0(config('base_dir'), '/results/ecp_at.csv'))

facet <- NULL

output_level <- 'patient'

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

## Single Site, Exploratory, No Time
```{r ss_exp_nt}

ecp_ss_exp_nt(process_output = no_time %>% filter(site == 'nationwide'),
              output_level = output_level,
              facet = facet)

```

## Multi Site, Exploratory, No Time
```{r ms_exp_nt}

ecp_ms_exp_nt(process_output = no_time,
              output_level = output_level,
              facet = facet)

```

## Single Site, Anomaly, No Time

```{r ss_anom_nt}

ss_anom <- ecp_process(cohort = results_tbl('jspa_cohort'),
                       site_list = c('chop'),
                       multi_or_single_site = 'single',
                       anomaly_or_exploratory = 'anomaly',
                       age_groups = read_codeset('age_group_definitions', 'iic'))

g <- ecp_ss_anom_nt(process_output = ss_anom,
                    facet = 'grp')

g

```

## Multi Site, Anomaly, No Time
```{r ms_anom_nt}

ecp_ms_anom_nt(process_output = no_time,
               output_level = output_level,
               facet = facet)

```

## Single Site, Exploratory, Across Time
```{r ss_exp_at}

g <- ecp_ss_exp_at(process_output = across_time %>% filter(site == 'nationwide'),
              output_level = output_level,
              facet = facet)

g

```

## Multi Site, Exploratory, Across Time
```{r ms_exp_at}

g <- ecp_ms_exp_at(process_output = across_time,
              output_level = output_level,
              facet = facet)

g
```

## Single Site, Anomaly, Across Time
```{r ss_anom_at}

ecp_ss_anom_at(process_output = across_time %>% filter(site == 'nationwide'),
              output_level = output_level,
              facet = facet)

```

## Multi Site, Anomaly, Across Time

```{r ms_anom_at}

ecp_ms_anom_at(process_output = across_time,
               output_level = output_level,
               facet = facet,
               mad_dev = 1)

```